### ISSUE TITLE
multiple shooting seems broken

### ISSUE THREAD

**Issue by benjaminabruzzo** [mayataka/CGMRES#1]
Hi, I just downloaded your code.  I am interested in porting this code to run with ROS, but I just started looking at your code.  I think there is something broken in the multiple shooting part, when I make and run the pendubot with multiple shooting, the control error and state error seem to be growing:

control_error = 33.3209, state_error = 1.78012
control_error = 31.3304, state_error = 1.73585
control_error = 38.7835, state_error = 1.72752
control_error = 10.2311, state_error = 2.50299
control_error = 606.258, state_error = 36.4873
control_error = 562246, state_error = 1.57417e+11
control_error = -nan, state_error = nan

**Comment by mayataka** [comment]
Thank you for pointing out the error.
To tell the truth, I uploaded incomplete code by mistake because I'm not familiar with github.
I fixed it, so please try it!
