### ISSUE TITLE
ask for help of the problem of hexacopter

### ISSUE THREAD

**Issue by qq1253002484** [mayataka/CGMRES#12]
Dear Katayama-san, I can't get the results of hexacopter. The other two experimental results can run successfully. But the simultion of hexacopter I get failed , it show that "The modified Gram-Schmidt breakdown at k=0" can you help me ?

**Comment by mayataka** [comment]
I have fixed the bug. The simulation filed because Newton's method for the initialization of the solution filed. 
It depends on the initial guess solution whether Newton's method works well or not. I have changed the initial guess solution in hexacopter.ipynb, so try it.

**Comment by qq1253002484** [comment]
Thanks
