### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by asadjadi** [mayataka/CGMRES#14]
Dear all,

Hereby I would like to inform you that when we have a system of equation in one dimension (dx = u - x) for instance. The plot section gives me the following message: 

> IndexError: tuple index out of range. 

`# Set dimensions of the state and the control input.`
`self.__dim_state = self.__state_data.shape[1]`

Could you please help me to solve this issue?

Thank you very much for your kind support and consideration.
Best regards,
Amin

**Comment by mayataka** [comment]
I fixed code to solve that issue.

**Comment by mayataka** [comment]
The latest version works well in my environment. 
Could you tell me whether it treats cases where dimx=1 or not?

**Comment by asadjadi** [comment]
Yes, the problem is solved and it is working properly. Thank you very much.

**Comment by mayataka** [comment]
Thank you for pointing out the bug.
