### ISSUE TITLE
Question on time step sensitivity

### ISSUE THREAD

**Issue by myozinaung** [mayataka/CGMRES#15]
Hello sir,

I was running the Cartpole example using different time step for numerical simulation.
The default time step for that problem is 0.001 s. When I try to run with the time step larger than 0.003, I found NaN values in the state_data from the simulation results. I think the sensitivity on the time step is very high due to the continuation assumption. Could you please make a discussion on this problem?

Best regards

**Comment by mayataka** [comment]
The shorter the sampling time (= time step in your word), the C/GMRES method tracks the optimal solution more accurately. The stabilization parameter zeta in the C/GMRES method is also crucial for computational stability. Typically, zeta must be the reciprocal of the sampling period. So if you set the sampling period 0.003 [s], then it may work well by setting zeta = 333. I'm sorry for forgetting to write about zeta.
