### ISSUE TITLE
Can't run "main.exe" after compilation

### ISSUE THREAD

**Issue by myozinaung** [mayataka/CGMRES#8]
![CMRES_error](https://user-images.githubusercontent.com/26024258/59907741-bd88ee00-9446-11e9-9072-d663f9234b78.PNG)
As shown in the attached image, the compilation seems successful but can't run. All the examples have the same problem for me.

**Comment by mayataka** [comment]
I have modified Python codes based on a guess that it is because of the wrong order of the link of libraries. It works well in OSX, however, I currently don't have Windows and I don't confirm whether it will work on Windows. So can you try the modified version?

**Comment by myozinaung** [comment]
I tested the previous codes on MacOS. It works well.
I am testing the updated codes on the Windows 10 now. 
The program seems successfully run. The new problem is that it doesn't create any solution file in the simulation_result folder. So, python can't do plotting.
![CGMRES_error2](https://user-images.githubusercontent.com/26024258/59995331-cde0d900-9691-11e9-9526-7061a930101c.PNG)

**Comment by mayataka** [comment]
I got the cause of the problem. I have added codes to treat the problem.

**Comment by myozinaung** [comment]
Hi sir, do you have the C/GMRES solvers for MATLAB/Simulink (or interface)?

**Comment by mayataka** [comment]
No, I don't.

**Comment by mayataka** [comment]
By the way, how about the latest version on Windows?

**Comment by myozinaung** [comment]
1. I've just tested the latest version. The same error occurs in all three example file. (screenshot attached).
![CGMRES_error3](https://user-images.githubusercontent.com/26024258/60151096-7029c980-9816-11e9-805c-1bf6c9f4f5cc.PNG)
  
   
  


2. The version **before** you added the extra files (....for_windows files) in the "simulator" folder >> its works well up to compilation. the only problem is that it does not generate solution files (*.dat files) inside the "simulation_result" folder. So I manually ran the "main.exe" file by double-clicking. Then I got the solution files and can continue with python plotting. (screenshot attached)
![CGMRES_error2b](https://user-images.githubusercontent.com/26024258/60151493-e7ac2880-9817-11e9-86d8-84ea0eed40e3.PNG)
  
  
  
  

3. The version **after** you added the extra files (....for_windows files) in the "simulator" folder >> it also works, but I still have to double-click "main.exe" to get the solution files. 
I also noticed an error when compilating the "pendubot"  >> **No such file or directory
 #include "multiple_shooting_cgmres_with_saturation_for_windows.hpp"**
That header file doesn't exit and it is called from the "multiple_shooting_cgmres_with_saturation_simulator_for_windows.hpp"
So, I replaced the with **#include "multiple_shooting_cgmres_with_saturation.hpp"**. And it works. (screenshot attached)
![CGMRES_error4](https://user-images.githubusercontent.com/26024258/60152069-0f03f500-981a-11e9-9be1-fc1066c78576.PNG)

**Comment by mayataka** [comment]
Thank you for cooperating to me. I have modified the first bug.
