### ISSUE TITLE
error on generating variables for problem formulation

### ISSUE THREAD

**Issue by Charvelau** [mayataka/CGMRES#9]
hi, I have some problems when running the juypter notebook,
during generating variables for problem formulation as:
`  File "<ipython-input-3-2de5aa16d31c>", line 2
    x = symbols(f'x[0:{dimx}]')
                             ^
SyntaxError: invalid syntax`

do you have any clue, thank you very much.

**Comment by mayataka** [comment]
I'm sorry, I have never faced such errors.
Can you tell me about your environment?

**Comment by Charvelau** [comment]
hi, I am on Ubuntu 16.04 LTS, python 3.5.2, sympy-1.4, jupyter 4.4.0
Thank you

**Comment by mayataka** [comment]
I got the cause of the error.
I notice that this code needs python 3.6 or later.
In ```x = symbols(f'x[0:{dimx}]')``` , I use ```f' {} ``` expression to embed integer in strings. 
This expression is introduced from python 3.6.
So, you need to update python, otherwise, you need to alternate the expression for the embedding so that it works on your environment. 
I'm sorry that I currently have no idea about the new expression. A simple solution may to update your python.

**Comment by Charvelau** [comment]
Thank you very much but I can't update python cause some other package
dependency.  Thank you so much and good night

**Comment by mayataka** [comment]
I came up with a modification.
Alternate cell 8 with the following codes.  

```
t = Symbol('t')  
x = symbols('x[0:%d]' %dimx)  
u = symbols(f'u[0:%d]' %(dimu+dimc))
lmd = symbols(f'lmd[0:%d]' %dimx)
```

**Comment by Charvelau** [comment]
Hi, I have modified condescendingly, but another error popped up, which is in stage cost definition.
`---> 11 L = sum(q[i]*(x[i] - x_ref[i])**2 for i in range(dimx))/2 + (r[0] * u[0]**2)/2 - dummy_weight*u[1]
`
`TypeError: 'Symbol' object does not support indexing
` 
but thank you so much for your quick respond and it:s too late for GMT 9, need to go to sleep and go for work early morning orz

**Comment by Charvelau** [comment]
or can I just write all the problem formulation in cpp files and embed them inside my own robot controller?
sorry for the trouble.

**Comment by Charvelau** [comment]
Dear Katayama-san, I checked my code again, and it turns out that it's my typo error causing the last problem, thank you very much. 
So the problem is solved.

**Comment by qq1253002484** [comment]
Dear Katayama-san, I can't get the results of hexacopter. The other two experimental results can run successfully. But the simultion of hexacopter I get failed , it show that "The modified Gram-Schmidt breakdown at k=0"  can you help me ?
